[package]
name = "autorenamer"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
nom = "7.1.3"
notify-rust = "4.11.3"
regex = "1.11.1"
