name: cargo_checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
  cargo_format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rust Format
      run: cargo fmt --check 
  cargo_clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      run: cargo clippy -- -D warnings
  cargo_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
  no_dbg:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check for "dbg"
      run: |
        if grep -r --exclude-dir={.*,.git} --exclude=*.{exe,bin,so,dll} "dbg" .; then
          echo "Found 'dbg' in the files."
          exit 1
        else
          echo "'dbg' not found in any files."
        fi
